# SPDX-FileCopyrightText: 2025 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 spatterlight
# SPDX-FileCopyrightText: 2026 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Ensure Autobrr paths exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0750"
    owner: "{{ autobrr_uid }}"
    group: "{{ autobrr_gid }}"
  with_items:
    - "{{ autobrr_base_path }}"
    - "{{ autobrr_data_path }}"

- name: Ensure Autobrr support files installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/{{ item }}.j2"
    dest: "{{ autobrr_base_path }}/{{ item }}"
    mode: "0640"
    owner: "{{ autobrr_uid }}"
    group: "{{ autobrr_gid }}"
  with_items:
    - env
    - labels
  register: autobrr_support_files_result

- name: Ensure Autobrr container image is pulled via community.docker.docker_image_pull
  when: devture_systemd_docker_base_container_image_pull_method == 'ansible-module'
  community.docker.docker_image_pull:
    name: "{{ autobrr_container_image }}"
    pull: always
  register: autobrr_container_image_pull_result_ansible_module
  retries: "{{ devture_playbook_help_container_retries_count }}"
  delay: "{{ devture_playbook_help_container_retries_delay }}"
  until: autobrr_container_image_pull_result_ansible_module is not failed

- name: Ensure Autobrr container image is pulled via ansible.builtin.command
  when: devture_systemd_docker_base_container_image_pull_method == 'command'
  ansible.builtin.command:
    cmd: "{{ devture_systemd_docker_base_host_command_docker }} pull {{ autobrr_container_image }}"
  register: autobrr_container_image_pull_result_command
  retries: "{{ devture_playbook_help_container_retries_count }}"
  delay: "{{ devture_playbook_help_container_retries_delay }}"
  until: autobrr_container_image_pull_result_command is not failed
  changed_when: "'Downloaded newer image' in autobrr_container_image_pull_result_command.stdout"

- name: Ensure Autobrr container network is created via community.docker.docker_network
  when: devture_systemd_docker_base_container_network_creation_method == 'ansible-module'
  community.docker.docker_network:
    enable_ipv6: "{{ devture_systemd_docker_base_ipv6_enabled }}"
    name: "{{ autobrr_container_network }}"
    driver: bridge
    driver_options: "{{ devture_systemd_docker_base_container_networks_driver_options }}"
  register: autobrr_network_creation_result

- name: Ensure Autobrr container network is created via ansible.builtin.command
  when: devture_systemd_docker_base_container_network_creation_method == 'command'
  ansible.builtin.command:
    cmd: >-
      {{ devture_systemd_docker_base_host_command_docker }} network create
      {% if devture_systemd_docker_base_ipv6_enabled %}--ipv6{% endif %}
      {{ devture_systemd_docker_base_container_networks_driver_options_string }}
      {{ autobrr_container_network }}
  register: autobrr_network_creation_result
  changed_when: autobrr_network_creation_result.rc == 0
  failed_when: autobrr_network_creation_result.rc != 0 and 'already exists' not in autobrr_network_creation_result.stderr

- name: Ensure Autobrr systemd service is present
  ansible.builtin.template:
    src: "{{ role_path }}/templates/systemd/autobrr.service.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/{{ autobrr_identifier }}.service"
    mode: "0644"
    lstrip_blocks: true
  register: autobrr_systemd_service_result

- name: Determine whether Autobrr needs a restart
  ansible.builtin.set_fact:
    autobrr_restart_necessary: >-
      {{
        autobrr_support_files_result.changed | default(false)
        or autobrr_systemd_service_result.changed | default(false)
        or autobrr_container_image_pull_result_ansible_module.changed | default(false)
        or autobrr_container_image_pull_result_command.changed | default(false)
      }}
