# SPDX-FileCopyrightText: 2025 spatterlight
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: Check existence of Autobrr systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ autobrr_identifier }}.service"
  register: autobrr_service_stat

- name: Uninstall Autobrr systemd services and files
  when: autobrr_service_stat.stat.exists | bool
  block:
    - name: Ensure Autobrr systemd service is stopped
      ansible.builtin.service:
        name: "{{ autobrr_identifier }}"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure Autobrr systemd service does not exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ autobrr_identifier }}.service"
        state: absent

    - name: Ensure Autobrr path does not exist
      ansible.builtin.file:
        path: "{{ autobrr_base_path }}"
        state: absent
