# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 spatterlight
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: (Deprecation) Catch and report renamed settings
  ansible.builtin.fail:
    msg: >-
      Your configuration contains a variable, which now has a different name.
      Please change your configuration to rename the variable (`{{ item.old }}` -> `{{ item.new }}`).
  when: "item.old in vars"
  with_items:
    - {'old': 'autobrr_container_additional_environment_variables', 'new': 'autobrr_environment_variables_additional_variables'}

- name: Fail if required Autobrr settings not defined
  ansible.builtin.fail:
    msg: >
      You need to define a required configuration setting (`{{ item }}`).
  when: "vars[item] | length == 0"
  with_items:
    - autobrr_uid
    - autobrr_gid
    - autobrr_hostname

- name: Fail if Autobrr architecture is not supported
  ansible.builtin.fail:
    msg: >
      Your configuration specifies a CPU architecture (`{{ autobrr_arch }}`) which is not currently supported.
      This Autobrr role also does not support self-building yet, so it's not possible to make use of it.
  when: "autobrr_arch not in ['amd64', 'arm64']"

- name: Validate Autobrr Traefik configuration
  when: autobrr_container_labels_traefik_enabled | bool
  block:
    - name: Fail if required Autobrr Traefik settings not defined
      ansible.builtin.fail:
        msg: >-
          You need to define a required configuration setting (`{{ item }}`).
      when: "vars[item] == ''"
      with_items:
        - autobrr_container_labels_traefik_hostname
        - autobrr_container_labels_traefik_path_prefix

    # We ensure it doesn't end with a slash, because we handle both (slash and no-slash).
    # Knowing that `autobrr_container_labels_traefik_path_prefix` does not end with a slash
    # ensures we know how to set these routes up without having to do "does it end with a slash" checks elsewhere.
    - name: Fail if autobrr_container_labels_traefik_path_prefix ends with a slash
      ansible.builtin.fail:
        msg: >-
          autobrr_container_labels_traefik_path_prefix (`{{ autobrr_container_labels_traefik_path_prefix }}`) must either be `/` or not end with a slash (e.g. `/autobrr`).
      when: "autobrr_container_labels_traefik_path_prefix != '/' and autobrr_container_labels_traefik_path_prefix[-1] == '/'"
